version: '3.4'
services:
    db:
        image: hugows007/mysql-docker
        command: mysqld --default-authentication-plugin=mysql_native_password
        restart: always
        build: 
            context: .
            dockerfile: ./mysql_docker/Dockerfile
        environment:
            TZ: America/Sao_Paulo
            MYSQL_ROOT_PASSWORD: docker123
            MYSQL_USER: root
            MYSQL_PASSWORD: docker123
            MYSQL_DATABASE: docker
        ports:
            - "3308:3306"
        networks:
            - network-spring
    spring-boot-rest:
        image: hugows007/spring-boot
        restart: always
        build: .
        working_dir: /spring-boot-rest-2
        environment:
            TZ: America/Sao_Paulo
            SPRING_BOOT_ENVIRONMENT: Production
        volumes:
            - ./:/spring-boot-rest-2
            - ~/.m2:/root/.m2
        ports:
            - "8080:8080"
        command: mvn clean spring-boot:run
        links:
            - db
        depends_on:
            - db
        networks:
            - network-spring
networks:
    network-spring:
        driver: bridge